name: Pipeline CI/CD - Prod

on: 
  push:
    branches:
      - main
  workflow _dispatch:

jobs:
  build-and-deploy:
    name: Iniciando build e deploy
    runs-on: ubuntu-latest
    enviroments: production
